### ISSUE TITLE
Support for requested_teams

### ISSUE THREAD

**Issue by AnthonyHerman** [DavideViolante/pr-reviews-reminder-action#10]
Currently only supports requested_reviewers, would be nice if there were support for requested_teams as well.

Edit by DavideViolante:
- [x] add support, testers are needed

**Comment by DavideViolante** [comment]
Thank you for this request, I didn't know about teams. I made a new [branch](https://github.com/DavideViolante/pr-reviews-reminder-action/commit/657b4b9d29431d1e590fbb49f18ed026309caa84) that you can use to test, I cant test it since I/we don't use them in the company.

To test the new branch just change the action to point at the branch instead of the version.
```yml
...
- uses: davideviolante/pr-reviews-reminder-action@requested_teams
...
```

Please let me know if it works and if you have any feedback.

**Comment by DavideViolante** [comment]
@AnthonyHerman have you tested the requested_teams branch eventually with teams and/or users?

**Comment by DavideViolante** [comment]
Oh thank you very much for testing, actually I was missing the pr.title in the branch (see "undefined"), now I fixed it and merged. 
You can now use the v1.5.0 in the yml file.

**Comment by AnthonyHerman** [comment]
Thank you!
